config:

  #################################### PRODUCT CONFIG #####################################

  namespace: <participant_identification>-dataphos

  retainResourceGroups: true

  resourceTags:
    team: dataphos
    env: test
  
  # schema registry chart config
  deploySchemaRegistry: false

  dataphos-schema-registry:
    registryReplicas:

  # schema registry validator chart config
  deploySchemaRegistryValidator: false

  dataphos-schema-registry-validator:
    xmlValidator:
      enable:

    csvValidator:
      enable:

    validator:
      validator:
        broker:
        destinationBroker:
        topic:
        consumerID:
        validTopic:
        deadletterTopic:
        replicas:

    # personalized validator
      <participant_identification>-validator:
        broker: servicebus
        destinationBroker: servicebus
        topic: <participant_identification>-input-topic
        consumerID: validator-sub
        validTopic: <participant_identification>-valid-topic
        deadletterTopic: <participant_identification>-deadletter-topic
        replicas: 1

  # persistor chart config
  deployPersistor: false

  dataphos-persistor:
    persistor:
      persistor:
        broker:
        topic:
        consumerID:
        storage:
        storageTargetID:
        indexer:
        replicas:
        storageMask:

    indexer:
      indexer:
        broker:
        topic:
        consumerID:
        replicas:
        consumerReplicas:
        storageSize:

    resubmitter:
      resubmitter:
        broker:
        storage: 
        indexer:

  ################################# INFRASTRUCTURE CONFIG #################################

  # provider config
  azure-native:location: italynorth

  # cluster config
  cluster:
    aks-cluster:
      type: aks
      name: dataphos-workshops_cluster-test
      resourceGroup: dataphos-workshops
      import: true


  # broker config
  brokers:
    servicebus:
      type: servicebus
      resourceGroup: dataphos-workshops
      azsbNamespace: dataphos-sb-ns
      retain: true

      topics:
        input-topic:
          retain: true
          subscriptions:
            <participant_identification>-val-sub: {}
        <participant_identification>-input-topic:
          subscriptions:
            validator-sub: {}
        <participant_identification>-valid-topic:
          subscriptions:
            persistor-sub: {}
        <participant_identification>-deadletter-topic:
          subscriptions:
            deadletter-topic-sub: {}
        <participant_identification>-indexer-topic:
          subscriptions:
            indexer-sub: {}
        <participant_identification>-resubmitter-topic:
          subscriptions:
            resubmitter-sub: {}

  # storage config
  storage:
    azure-blob-storage:
      type: abs
      resourceGroup: dataphos-workshops
      accountStorageID: dataphosworkshops
      retain: true

      buckets:
        <participant_identification>-data-lake: {}
