config:

  #################################### PRODUCT CONFIG #####################################

  namespace: hosts-dataphos
  # component selection
  deploySchemaRegistry: true
  deploySchemaRegistryValidator: true
  deployPersistor: true

  retainResourceGroups: true

  resourceTags:
    team: dataphos
    env: test

  # schema registry chart config
  dataphos-schema-registry:
    registryReplicas: 1

    # History database.
    database:
      name: postgres
      username: postgres
      password: POSTGRES_PASSWORD

  # schema registry validator chart config
  dataphos-schema-registry-validator:
    xmlValidator:
      enable: false

    csvValidator:
      enable: false

    validator:
      validator:
        broker: servicebus
        destinationBroker: servicebus
        topic: input-topic
        consumerID: hosts-val-sub
        validTopic: hosts-valid-topic
        deadletterTopic: hosts-deadletter-topic
        replicas: 1

    # personalized validator
      hosts-validator:
        broker: servicebus
        destinationBroker: servicebus
        topic: hosts-input-topic
        consumerID: validator-sub
        validTopic: hosts-valid-topic
        deadletterTopic: hosts-deadletter-topic
        replicas: 1

  # persistor chart config
  dataphos-persistor:
    persistor:
      persistor:
        broker: servicebus
        topic: hosts-valid-topic
        consumerID: persistor-sub
        storage: azure-blob-storage
        storageTargetID: hosts-data-lake
        indexer: indexer # Indexer reference (if not set the indexer plugin is disabled)
        replicas: 1
        storageCustomValues: "customValue1:hosts"
        storageMask: "customValue1/{schemaId}/{versionId}/year/month/day/hour"

    indexer:
      indexer:
        broker: servicebus
        topic: hosts-indexer-topic
        consumerID: indexer-sub
        replicas: 1 # Scale the service exposing the metadata
        consumerReplicas: 1 # Scale the consumers reading and storing the metadata
        storageSize: 1Gi

    resubmitter:
      resubmitter:
        broker: servicebus
        storage: azure-blob-storage
        indexer: indexer

  ################################# INFRASTRUCTURE CONFIG #################################

  # provider config
  azure-native:location: italynorth

  # cluster config
  cluster:
    aks-cluster:
      type: aks
      name: dataphos-workshops_cluster-test
      resourceGroup: dataphos-workshops
      import: true


  # broker config
  brokers:
    servicebus:
      type: servicebus
      resourceGroup: dataphos-workshops
      azsbNamespace: dataphos-sb-ns
      retain: true

      topics:
        input-topic:
          retain: true
          subscriptions:
            hosts-val-sub: {}
        hosts-input-topic:
          subscriptions:
            validator-sub: {}
        hosts-valid-topic:
          subscriptions:
            persistor-sub: {}
        hosts-deadletter-topic:
          subscriptions:
            deadletter-topic-sub: {}
        hosts-indexer-topic:
          subscriptions:
            indexer-sub: {}
        hosts-resubmitter-topic:
          subscriptions:
            resubmitter-sub: {}

  # storage config
  storage:
    azure-blob-storage:
      type: abs
      resourceGroup: dataphos-workshops
      accountStorageID: dataphosworkshops
      retain: true

      buckets:
        hosts-data-lake: {}
